name: 'Lint'

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Install python'
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'

      - name: 'Install software'
        run: |
          sudo apt -y install shellcheck
          python3 -m pip install black

      - name: 'Lint shell code'
        run: |
          shellcheck *.sh

      - name: 'Lint python code'
        run: |
          black --check *.py
